modLoader="javafml"
loaderVersion="[43,)"
license="Apache License version 2.0"

[[mods]]
modId="modsupertool"
version="2.4.5"
displayName="Modsuper tool"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://github.com/Samlouploup/mcreator-supertool"
authors="Samuel Feller"

[[dependencies.modsupertool]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2]"
    ordering="NONE"
    side="BOTH"




