
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.modabusif.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;
import net.minecraftforge.common.ForgeSpawnEggItem;

import net.minecraft.world.level.block.Block;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.CreativeModeTab;
import net.minecraft.world.item.BlockItem;

import net.mcreator.modabusif.item.VentreDeTortueItem;
import net.mcreator.modabusif.item.TerreItem;
import net.mcreator.modabusif.item.SupremeItem;
import net.mcreator.modabusif.item.SuperferItem;
import net.mcreator.modabusif.item.SuperStarItem;
import net.mcreator.modabusif.item.SuperPoudreDeBlazeItem;
import net.mcreator.modabusif.item.SuperOeilDeLendItem;
import net.mcreator.modabusif.item.SuperKatanaItem;
import net.mcreator.modabusif.item.SuperEcailleItem;
import net.mcreator.modabusif.item.SamouraiItem;
import net.mcreator.modabusif.item.RoiDesMersItem;
import net.mcreator.modabusif.item.PlaqueDeSamouraiItem;
import net.mcreator.modabusif.item.PiochebrulanteItem;
import net.mcreator.modabusif.item.PiocheWitherItem;
import net.mcreator.modabusif.item.PiocheSupremeItem;
import net.mcreator.modabusif.item.PiocheParfaiteItem;
import net.mcreator.modabusif.item.PiocheInfernalItem;
import net.mcreator.modabusif.item.PiocheEnflameItem;
import net.mcreator.modabusif.item.PiocheEnTerreItem;
import net.mcreator.modabusif.item.PiocheEnPierreItem;
import net.mcreator.modabusif.item.PiocheEnFerItem;
import net.mcreator.modabusif.item.PiocheEnEarthenergieItem;
import net.mcreator.modabusif.item.PiocheEmbraseItem;
import net.mcreator.modabusif.item.PiocheDuPharaonItem;
import net.mcreator.modabusif.item.PiocheDivineItem;
import net.mcreator.modabusif.item.PiocheArdenteItem;
import net.mcreator.modabusif.item.PierreItem;
import net.mcreator.modabusif.item.PharaonItem;
import net.mcreator.modabusif.item.PerlePafaiteItem;
import net.mcreator.modabusif.item.ParfaitItem;
import net.mcreator.modabusif.item.PainDeViandeMagiqueItem;
import net.mcreator.modabusif.item.OrbeSupremeItem;
import net.mcreator.modabusif.item.OeilDuWitherFouItem;
import net.mcreator.modabusif.item.NaturelItem;
import net.mcreator.modabusif.item.MaitreDuNetherItem;
import net.mcreator.modabusif.item.LingotParfaitItem;
import net.mcreator.modabusif.item.LeCodexItem;
import net.mcreator.modabusif.item.FlammeMagiqueItem;
import net.mcreator.modabusif.item.FlameParfaiteItem;
import net.mcreator.modabusif.item.FilConducteurItem;
import net.mcreator.modabusif.item.EpeeParfaiteeItem;
import net.mcreator.modabusif.item.EpeeParfaiteItem;
import net.mcreator.modabusif.item.EpeeEnTerreItem;
import net.mcreator.modabusif.item.EpeeEnSuperPierreItem;
import net.mcreator.modabusif.item.EpeeEnSuperFerItem;
import net.mcreator.modabusif.item.EpeeEnSuperBoisItem;
import net.mcreator.modabusif.item.EpeeEnEarthenergieItem;
import net.mcreator.modabusif.item.EpeeDuPharaonItem;
import net.mcreator.modabusif.item.EpeeDuNetherItem;
import net.mcreator.modabusif.item.EpeeDivineItem;
import net.mcreator.modabusif.item.EpeeDeLendItem;
import net.mcreator.modabusif.item.EnderItem;
import net.mcreator.modabusif.item.EarthernergieItem;
import net.mcreator.modabusif.item.DivinItem;
import net.mcreator.modabusif.item.DecapitarbreItem;
import net.mcreator.modabusif.item.CoureurDesMersItem;
import net.mcreator.modabusif.item.ConducteurArmorItem;
import net.mcreator.modabusif.item.CoeurdotomateItem;
import net.mcreator.modabusif.item.CoeurDeFeuItem;
import net.mcreator.modabusif.item.CisaillesDElectrienItem;
import net.mcreator.modabusif.item.CisaillesAEcailleItem;
import net.mcreator.modabusif.item.CasseVideItem;
import net.mcreator.modabusif.item.CanneparfaiteItem;
import net.mcreator.modabusif.item.CanneSupremeItem;
import net.mcreator.modabusif.item.CanneEnEarthenergieItem;
import net.mcreator.modabusif.item.CanneDuPharaonItem;
import net.mcreator.modabusif.item.CanneDivineItem;
import net.mcreator.modabusif.item.CanneAPecheEnTerreItem;
import net.mcreator.modabusif.item.CanneAPecheEnSuperFerItem;
import net.mcreator.modabusif.item.CanneAPecheEnPierreItem;
import net.mcreator.modabusif.item.BuilderItem;
import net.mcreator.modabusif.item.BouteilleMondeItem;
import net.mcreator.modabusif.item.BatonDuPharaonItem;
import net.mcreator.modabusif.item.AutomateItem;
import net.mcreator.modabusif.item.AntiterreeItem;
import net.mcreator.modabusif.item.AntiterreItem;
import net.mcreator.modabusif.item.AntisableItem;
import net.mcreator.modabusif.item.AntigraviereItem;
import net.mcreator.modabusif.item.AntiargileItem;
import net.mcreator.modabusif.item.AntiGravierItem;
import net.mcreator.modabusif.item.AmeMondeItem;
import net.mcreator.modabusif.ModsupertoolMod;

public class ModsupertoolModItems {
	public static final DeferredRegister<Item> REGISTRY = DeferredRegister.create(ForgeRegistries.ITEMS, ModsupertoolMod.MODID);
	public static final RegistryObject<Item> TERRE_HELMET = REGISTRY.register("terre_helmet", () -> new TerreItem.Helmet());
	public static final RegistryObject<Item> TERRE_CHESTPLATE = REGISTRY.register("terre_chestplate", () -> new TerreItem.Chestplate());
	public static final RegistryObject<Item> TERRE_LEGGINGS = REGISTRY.register("terre_leggings", () -> new TerreItem.Leggings());
	public static final RegistryObject<Item> TERRE_BOOTS = REGISTRY.register("terre_boots", () -> new TerreItem.Boots());
	public static final RegistryObject<Item> PIERRE_HELMET = REGISTRY.register("pierre_helmet", () -> new PierreItem.Helmet());
	public static final RegistryObject<Item> PIERRE_CHESTPLATE = REGISTRY.register("pierre_chestplate", () -> new PierreItem.Chestplate());
	public static final RegistryObject<Item> PIERRE_LEGGINGS = REGISTRY.register("pierre_leggings", () -> new PierreItem.Leggings());
	public static final RegistryObject<Item> PIERRE_BOOTS = REGISTRY.register("pierre_boots", () -> new PierreItem.Boots());
	public static final RegistryObject<Item> SUPERPIERRE = block(ModsupertoolModBlocks.SUPERPIERRE, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> SUPERFER_HELMET = REGISTRY.register("superfer_helmet", () -> new SuperferItem.Helmet());
	public static final RegistryObject<Item> SUPERFER_CHESTPLATE = REGISTRY.register("superfer_chestplate", () -> new SuperferItem.Chestplate());
	public static final RegistryObject<Item> SUPERFER_LEGGINGS = REGISTRY.register("superfer_leggings", () -> new SuperferItem.Leggings());
	public static final RegistryObject<Item> SUPERFER_BOOTS = REGISTRY.register("superfer_boots", () -> new SuperferItem.Boots());
	public static final RegistryObject<Item> SUPER_FER_B = block(ModsupertoolModBlocks.SUPER_FER_B, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> EARTHERNERGIE_HELMET = REGISTRY.register("earthernergie_helmet", () -> new EarthernergieItem.Helmet());
	public static final RegistryObject<Item> EARTHERNERGIE_CHESTPLATE = REGISTRY.register("earthernergie_chestplate", () -> new EarthernergieItem.Chestplate());
	public static final RegistryObject<Item> EARTHERNERGIE_LEGGINGS = REGISTRY.register("earthernergie_leggings", () -> new EarthernergieItem.Leggings());
	public static final RegistryObject<Item> EARTHERNERGIE_BOOTS = REGISTRY.register("earthernergie_boots", () -> new EarthernergieItem.Boots());
	public static final RegistryObject<Item> SUPEREMERAUDE = block(ModsupertoolModBlocks.SUPEREMERAUDE, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> SUPERREDSTONE = block(ModsupertoolModBlocks.SUPERREDSTONE, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> EARTHENERGIE = block(ModsupertoolModBlocks.EARTHENERGIE, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> PHARAON_HELMET = REGISTRY.register("pharaon_helmet", () -> new PharaonItem.Helmet());
	public static final RegistryObject<Item> PHARAON_CHESTPLATE = REGISTRY.register("pharaon_chestplate", () -> new PharaonItem.Chestplate());
	public static final RegistryObject<Item> PHARAON_LEGGINGS = REGISTRY.register("pharaon_leggings", () -> new PharaonItem.Leggings());
	public static final RegistryObject<Item> PHARAON_BOOTS = REGISTRY.register("pharaon_boots", () -> new PharaonItem.Boots());
	public static final RegistryObject<Item> SUPEROR = block(ModsupertoolModBlocks.SUPEROR, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> SUPER_LAPIS = block(ModsupertoolModBlocks.SUPER_LAPIS, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> PHARAONB = block(ModsupertoolModBlocks.PHARAONB, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> PHARAON_MAUDIT_SPAWN_EGG = REGISTRY.register("pharaon_maudit_spawn_egg",
			() -> new ForgeSpawnEggItem(ModsupertoolModEntities.PHARAON_MAUDIT, -256, -16776961, new Item.Properties().tab(ModsupertoolModTabs.TAB_ITEMS_DIVERS_SUPER_TOOLS)));
	public static final RegistryObject<Item> BATON_DU_PHARAON = REGISTRY.register("baton_du_pharaon", () -> new BatonDuPharaonItem());
	public static final RegistryObject<Item> SUPREME_HELMET = REGISTRY.register("supreme_helmet", () -> new SupremeItem.Helmet());
	public static final RegistryObject<Item> SUPREME_CHESTPLATE = REGISTRY.register("supreme_chestplate", () -> new SupremeItem.Chestplate());
	public static final RegistryObject<Item> SUPREME_LEGGINGS = REGISTRY.register("supreme_leggings", () -> new SupremeItem.Leggings());
	public static final RegistryObject<Item> SUPREME_BOOTS = REGISTRY.register("supreme_boots", () -> new SupremeItem.Boots());
	public static final RegistryObject<Item> ORBE_SUPREME = REGISTRY.register("orbe_supreme", () -> new OrbeSupremeItem());
	public static final RegistryObject<Item> SUPER_DIAMANT = block(ModsupertoolModBlocks.SUPER_DIAMANT, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> SUPREMEB = block(ModsupertoolModBlocks.SUPREMEB, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> PARFAIT_HELMET = REGISTRY.register("parfait_helmet", () -> new ParfaitItem.Helmet());
	public static final RegistryObject<Item> PARFAIT_CHESTPLATE = REGISTRY.register("parfait_chestplate", () -> new ParfaitItem.Chestplate());
	public static final RegistryObject<Item> PARFAIT_LEGGINGS = REGISTRY.register("parfait_leggings", () -> new ParfaitItem.Leggings());
	public static final RegistryObject<Item> PARFAIT_BOOTS = REGISTRY.register("parfait_boots", () -> new ParfaitItem.Boots());
	public static final RegistryObject<Item> FLAME_PARFAITE = REGISTRY.register("flame_parfaite", () -> new FlameParfaiteItem());
	public static final RegistryObject<Item> PERLE_PAFAITE = REGISTRY.register("perle_pafaite", () -> new PerlePafaiteItem());
	public static final RegistryObject<Item> SUPER_NETHERITE = block(ModsupertoolModBlocks.SUPER_NETHERITE, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> BLOC_PARFAIT = block(ModsupertoolModBlocks.BLOC_PARFAIT, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> LINGOT_PARFAIT = REGISTRY.register("lingot_parfait", () -> new LingotParfaitItem());
	public static final RegistryObject<Item> SUPER_BOIS = block(ModsupertoolModBlocks.SUPER_BOIS, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> BOIS_BENI = block(ModsupertoolModBlocks.BOIS_BENI, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> NATUREL_HELMET = REGISTRY.register("naturel_helmet", () -> new NaturelItem.Helmet());
	public static final RegistryObject<Item> NATUREL_CHESTPLATE = REGISTRY.register("naturel_chestplate", () -> new NaturelItem.Chestplate());
	public static final RegistryObject<Item> NATUREL_LEGGINGS = REGISTRY.register("naturel_leggings", () -> new NaturelItem.Leggings());
	public static final RegistryObject<Item> NATUREL_BOOTS = REGISTRY.register("naturel_boots", () -> new NaturelItem.Boots());
	public static final RegistryObject<Item> BOUTEILLE_MONDE = REGISTRY.register("bouteille_monde", () -> new BouteilleMondeItem());
	public static final RegistryObject<Item> AME_MONDE = REGISTRY.register("ame_monde", () -> new AmeMondeItem());
	public static final RegistryObject<Item> SUPER_STAR = REGISTRY.register("super_star", () -> new SuperStarItem());
	public static final RegistryObject<Item> DIVIN_HELMET = REGISTRY.register("divin_helmet", () -> new DivinItem.Helmet());
	public static final RegistryObject<Item> DIVIN_CHESTPLATE = REGISTRY.register("divin_chestplate", () -> new DivinItem.Chestplate());
	public static final RegistryObject<Item> DIVIN_LEGGINGS = REGISTRY.register("divin_leggings", () -> new DivinItem.Leggings());
	public static final RegistryObject<Item> DIVIN_BOOTS = REGISTRY.register("divin_boots", () -> new DivinItem.Boots());
	public static final RegistryObject<Item> PIOCHE_EN_TERRE = REGISTRY.register("pioche_en_terre", () -> new PiocheEnTerreItem());
	public static final RegistryObject<Item> PIOCHE_EN_PIERRE = REGISTRY.register("pioche_en_pierre", () -> new PiocheEnPierreItem());
	public static final RegistryObject<Item> PIOCHE_EN_FER = REGISTRY.register("pioche_en_fer", () -> new PiocheEnFerItem());
	public static final RegistryObject<Item> PIOCHE_EN_EARTHENERGIE = REGISTRY.register("pioche_en_earthenergie", () -> new PiocheEnEarthenergieItem());
	public static final RegistryObject<Item> PIOCHE_DU_PHARAON = REGISTRY.register("pioche_du_pharaon", () -> new PiocheDuPharaonItem());
	public static final RegistryObject<Item> PIOCHE_SUPREME = REGISTRY.register("pioche_supreme", () -> new PiocheSupremeItem());
	public static final RegistryObject<Item> PIOCHE_PARFAITE = REGISTRY.register("pioche_parfaite", () -> new PiocheParfaiteItem());
	public static final RegistryObject<Item> PIOCHE_DIVINE = REGISTRY.register("pioche_divine", () -> new PiocheDivineItem());
	public static final RegistryObject<Item> PIOCHEBRULANTE = REGISTRY.register("piochebrulante", () -> new PiochebrulanteItem());
	public static final RegistryObject<Item> PIOCHE_ARDENTE = REGISTRY.register("pioche_ardente", () -> new PiocheArdenteItem());
	public static final RegistryObject<Item> PIOCHE_ENFLAME = REGISTRY.register("pioche_enflame", () -> new PiocheEnflameItem());
	public static final RegistryObject<Item> PIOCHE_EMBRASE = REGISTRY.register("pioche_embrase", () -> new PiocheEmbraseItem());
	public static final RegistryObject<Item> PIOCHE_INFERNAL = REGISTRY.register("pioche_infernal", () -> new PiocheInfernalItem());
	public static final RegistryObject<Item> ANTITERRE = REGISTRY.register("antiterre", () -> new AntiterreItem());
	public static final RegistryObject<Item> DECAPITARBRE = REGISTRY.register("decapitarbre", () -> new DecapitarbreItem());
	public static final RegistryObject<Item> ROI_DES_MERS_HELMET = REGISTRY.register("roi_des_mers_helmet", () -> new RoiDesMersItem.Helmet());
	public static final RegistryObject<Item> ROI_DES_MERS_CHESTPLATE = REGISTRY.register("roi_des_mers_chestplate", () -> new RoiDesMersItem.Chestplate());
	public static final RegistryObject<Item> ROI_DES_MERS_LEGGINGS = REGISTRY.register("roi_des_mers_leggings", () -> new RoiDesMersItem.Leggings());
	public static final RegistryObject<Item> ROI_DES_MERS_BOOTS = REGISTRY.register("roi_des_mers_boots", () -> new RoiDesMersItem.Boots());
	public static final RegistryObject<Item> SUPER_ECAILLE = REGISTRY.register("super_ecaille", () -> new SuperEcailleItem());
	public static final RegistryObject<Item> CISAILLES_A_ECAILLE = REGISTRY.register("cisailles_a_ecaille", () -> new CisaillesAEcailleItem());
	public static final RegistryObject<Item> VENTRE_DE_TORTUE = REGISTRY.register("ventre_de_tortue", () -> new VentreDeTortueItem());
	public static final RegistryObject<Item> EPEE_EN_TERRE = REGISTRY.register("epee_en_terre", () -> new EpeeEnTerreItem());
	public static final RegistryObject<Item> EPEE_EN_SUPER_BOIS = REGISTRY.register("epee_en_super_bois", () -> new EpeeEnSuperBoisItem());
	public static final RegistryObject<Item> EPEE_DE_LEND = REGISTRY.register("epee_de_lend", () -> new EpeeDeLendItem());
	public static final RegistryObject<Item> SUPER_OEIL_DE_LEND = REGISTRY.register("super_oeil_de_lend", () -> new SuperOeilDeLendItem());
	public static final RegistryObject<Item> EPEE_DU_NETHER = REGISTRY.register("epee_du_nether", () -> new EpeeDuNetherItem());
	public static final RegistryObject<Item> SUPER_POUDRE_DE_BLAZE = REGISTRY.register("super_poudre_de_blaze", () -> new SuperPoudreDeBlazeItem());
	public static final RegistryObject<Item> EPEE_EN_SUPER_PIERRE = REGISTRY.register("epee_en_super_pierre", () -> new EpeeEnSuperPierreItem());
	public static final RegistryObject<Item> PIOCHE_WITHER = REGISTRY.register("pioche_wither", () -> new PiocheWitherItem());
	public static final RegistryObject<Item> OEIL_DU_WITHER_FOU = REGISTRY.register("oeil_du_wither_fou", () -> new OeilDuWitherFouItem());
	public static final RegistryObject<Item> EPEE_EN_SUPER_FER = REGISTRY.register("epee_en_super_fer", () -> new EpeeEnSuperFerItem());
	public static final RegistryObject<Item> EPEE_EN_EARTHENERGIE = REGISTRY.register("epee_en_earthenergie", () -> new EpeeEnEarthenergieItem());
	public static final RegistryObject<Item> EPEE_DU_PHARAON = REGISTRY.register("epee_du_pharaon", () -> new EpeeDuPharaonItem());
	public static final RegistryObject<Item> EPEE_PARFAITE = REGISTRY.register("epee_parfaite", () -> new EpeeParfaiteItem());
	public static final RegistryObject<Item> EPEE_PARFAITEE = REGISTRY.register("epee_parfaitee", () -> new EpeeParfaiteeItem());
	public static final RegistryObject<Item> EPEE_DIVINE = REGISTRY.register("epee_divine", () -> new EpeeDivineItem());
	public static final RegistryObject<Item> SUPER_CERISIER = block(ModsupertoolModBlocks.SUPER_CERISIER, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> SUPER_KATANA = REGISTRY.register("super_katana", () -> new SuperKatanaItem());
	public static final RegistryObject<Item> PLAQUE_DE_SAMOURAI = REGISTRY.register("plaque_de_samourai", () -> new PlaqueDeSamouraiItem());
	public static final RegistryObject<Item> SAMOURAI_HELMET = REGISTRY.register("samourai_helmet", () -> new SamouraiItem.Helmet());
	public static final RegistryObject<Item> SAMOURAI_CHESTPLATE = REGISTRY.register("samourai_chestplate", () -> new SamouraiItem.Chestplate());
	public static final RegistryObject<Item> SAMOURAI_LEGGINGS = REGISTRY.register("samourai_leggings", () -> new SamouraiItem.Leggings());
	public static final RegistryObject<Item> SAMOURAI_BOOTS = REGISTRY.register("samourai_boots", () -> new SamouraiItem.Boots());
	public static final RegistryObject<Item> ANTISABLE = REGISTRY.register("antisable", () -> new AntisableItem());
	public static final RegistryObject<Item> ANTI_GRAVIER = REGISTRY.register("anti_gravier", () -> new AntiGravierItem());
	public static final RegistryObject<Item> GOLEM_COROMPU_SPAWN_EGG = REGISTRY.register("golem_corompu_spawn_egg",
			() -> new ForgeSpawnEggItem(ModsupertoolModEntities.GOLEM_COROMPU, -10066330, -16777216, new Item.Properties().tab(ModsupertoolModTabs.TAB_ITEMS_DIVERS_SUPER_TOOLS)));
	public static final RegistryObject<Item> SUPER_PLANCHES = block(ModsupertoolModBlocks.SUPER_PLANCHES, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> ANTITERREE = REGISTRY.register("antiterree", () -> new AntiterreeItem());
	public static final RegistryObject<Item> CASSE_VIDE = REGISTRY.register("casse_vide", () -> new CasseVideItem());
	public static final RegistryObject<Item> MAITRE_DU_NETHER_HELMET = REGISTRY.register("maitre_du_nether_helmet", () -> new MaitreDuNetherItem.Helmet());
	public static final RegistryObject<Item> MAITRE_DU_NETHER_CHESTPLATE = REGISTRY.register("maitre_du_nether_chestplate", () -> new MaitreDuNetherItem.Chestplate());
	public static final RegistryObject<Item> MAITRE_DU_NETHER_LEGGINGS = REGISTRY.register("maitre_du_nether_leggings", () -> new MaitreDuNetherItem.Leggings());
	public static final RegistryObject<Item> MAITRE_DU_NETHER_BOOTS = REGISTRY.register("maitre_du_nether_boots", () -> new MaitreDuNetherItem.Boots());
	public static final RegistryObject<Item> FLAMME_MAGIQUE = REGISTRY.register("flamme_magique", () -> new FlammeMagiqueItem());
	public static final RegistryObject<Item> COUREUR_DES_MERS_BOOTS = REGISTRY.register("coureur_des_mers_boots", () -> new CoureurDesMersItem.Boots());
	public static final RegistryObject<Item> CANNE_A_PECHE_EN_TERRE = REGISTRY.register("canne_a_peche_en_terre", () -> new CanneAPecheEnTerreItem());
	public static final RegistryObject<Item> CANNE_A_PECHE_EN_PIERRE = REGISTRY.register("canne_a_peche_en_pierre", () -> new CanneAPecheEnPierreItem());
	public static final RegistryObject<Item> CANNE_A_PECHE_EN_SUPER_FER = REGISTRY.register("canne_a_peche_en_super_fer", () -> new CanneAPecheEnSuperFerItem());
	public static final RegistryObject<Item> CANNE_EN_EARTHENERGIE = REGISTRY.register("canne_en_earthenergie", () -> new CanneEnEarthenergieItem());
	public static final RegistryObject<Item> CANNE_DU_PHARAON = REGISTRY.register("canne_du_pharaon", () -> new CanneDuPharaonItem());
	public static final RegistryObject<Item> CANNE_SUPREME = REGISTRY.register("canne_supreme", () -> new CanneSupremeItem());
	public static final RegistryObject<Item> CANNEPARFAITE = REGISTRY.register("canneparfaite", () -> new CanneparfaiteItem());
	public static final RegistryObject<Item> CANNE_DIVINE = REGISTRY.register("canne_divine", () -> new CanneDivineItem());
	public static final RegistryObject<Item> ENDER_HELMET = REGISTRY.register("ender_helmet", () -> new EnderItem.Helmet());
	public static final RegistryObject<Item> ENDER_CHESTPLATE = REGISTRY.register("ender_chestplate", () -> new EnderItem.Chestplate());
	public static final RegistryObject<Item> ENDER_LEGGINGS = REGISTRY.register("ender_leggings", () -> new EnderItem.Leggings());
	public static final RegistryObject<Item> ENDER_BOOTS = REGISTRY.register("ender_boots", () -> new EnderItem.Boots());
	public static final RegistryObject<Item> BUILDER_HELMET = REGISTRY.register("builder_helmet", () -> new BuilderItem.Helmet());
	public static final RegistryObject<Item> BUILDER_CHESTPLATE = REGISTRY.register("builder_chestplate", () -> new BuilderItem.Chestplate());
	public static final RegistryObject<Item> BUILDER_LEGGINGS = REGISTRY.register("builder_leggings", () -> new BuilderItem.Leggings());
	public static final RegistryObject<Item> BUILDER_BOOTS = REGISTRY.register("builder_boots", () -> new BuilderItem.Boots());
	public static final RegistryObject<Item> SUPER_CUIVRE = block(ModsupertoolModBlocks.SUPER_CUIVRE, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> CISAILLES_D_ELECTRIEN = REGISTRY.register("cisailles_d_electrien", () -> new CisaillesDElectrienItem());
	public static final RegistryObject<Item> FIL_CONDUCTEUR = REGISTRY.register("fil_conducteur", () -> new FilConducteurItem());
	public static final RegistryObject<Item> BLOC_CONDUCTEUR = block(ModsupertoolModBlocks.BLOC_CONDUCTEUR, ModsupertoolModTabs.TAB_SUPER_BLOC);
	public static final RegistryObject<Item> CONDUCTEUR_ARMOR_HELMET = REGISTRY.register("conducteur_armor_helmet", () -> new ConducteurArmorItem.Helmet());
	public static final RegistryObject<Item> CONDUCTEUR_ARMOR_CHESTPLATE = REGISTRY.register("conducteur_armor_chestplate", () -> new ConducteurArmorItem.Chestplate());
	public static final RegistryObject<Item> CONDUCTEUR_ARMOR_LEGGINGS = REGISTRY.register("conducteur_armor_leggings", () -> new ConducteurArmorItem.Leggings());
	public static final RegistryObject<Item> CONDUCTEUR_ARMOR_BOOTS = REGISTRY.register("conducteur_armor_boots", () -> new ConducteurArmorItem.Boots());
	public static final RegistryObject<Item> AUTOMATE_HELMET = REGISTRY.register("automate_helmet", () -> new AutomateItem.Helmet());
	public static final RegistryObject<Item> AUTOMATE_CHESTPLATE = REGISTRY.register("automate_chestplate", () -> new AutomateItem.Chestplate());
	public static final RegistryObject<Item> AUTOMATE_LEGGINGS = REGISTRY.register("automate_leggings", () -> new AutomateItem.Leggings());
	public static final RegistryObject<Item> AUTOMATE_BOOTS = REGISTRY.register("automate_boots", () -> new AutomateItem.Boots());
	public static final RegistryObject<Item> COEURDOTOMATE = REGISTRY.register("coeurdotomate", () -> new CoeurdotomateItem());
	public static final RegistryObject<Item> ANTIGRAVIERE = REGISTRY.register("antigraviere", () -> new AntigraviereItem());
	public static final RegistryObject<Item> ANTIARGILE = REGISTRY.register("antiargile", () -> new AntiargileItem());
	public static final RegistryObject<Item> LE_CODEX = REGISTRY.register("le_codex", () -> new LeCodexItem());
	public static final RegistryObject<Item> GARDIEN_DU_TEMPLE_SPAWN_EGG = REGISTRY.register("gardien_du_temple_spawn_egg",
			() -> new ForgeSpawnEggItem(ModsupertoolModEntities.GARDIEN_DU_TEMPLE, -65536, -16711783, new Item.Properties().tab(ModsupertoolModTabs.TAB_ITEMS_DIVERS_SUPER_TOOLS)));
	public static final RegistryObject<Item> COEUR_DE_FEU = REGISTRY.register("coeur_de_feu", () -> new CoeurDeFeuItem());
	public static final RegistryObject<Item> PAIN_DE_VIANDE_MAGIQUE = REGISTRY.register("pain_de_viande_magique", () -> new PainDeViandeMagiqueItem());

	private static RegistryObject<Item> block(RegistryObject<Block> block, CreativeModeTab tab) {
		return REGISTRY.register(block.getId().getPath(), () -> new BlockItem(block.get(), new Item.Properties().tab(tab)));
	}
}
